#!/usr/bin/perl

# ===================================================================
# File:		scheduled-tasks/send-newsletters
# Project:	ShinyCMS
# Purpose:	Check for scheduled newsletter mailshots and send them
# Author:	Denny de la Haye <2010@denny.me>
# 
# ShinyCMS is free software. You can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License.
# ===================================================================

use strict;
use warnings;

# Local modules
use lib 'lib/';
use ShinyCMS;
use ShinyCMS::Schema;

# CPAN modules
use File::Pid;


# Exit if already running
my $pidfile = File::Pid->new({
	file => '/tmp/shinycms-send-newsletters.pid',
});

$pidfile->write;

if ( my $num = $pidfile->running ) {
	die "Already running: $num\n";
}


# Get a database connection
my $schema = ShinyCMS::Schema->connect(
	ShinyCMS->config->{ 'Model::DB' }->{ connect_info }
);

# Get the current date and time
my $now = DateTime->now;

# Find newsletters that are marked or scheduled for sending
my @newsletters = $schema->resultset( 'Newsletter' )->search(
	[
		{ status => 'Queued'         },
		{ sent   => { '<=' => $now } },
	]
);

# Loop through the newsletters
foreach my $newsletter ( @$newsletters ) {
	print $newsletter->title, "\n";
	
	# Find the recipients
	
	
	# Send the newsletter
	
	
	# Change the status appropriately
	$newsletter->update({ status => 'Sent' });
}

# Remove the PID file
$pidfile->remove;

